### ISSUE TITLE
Feature: Ability to fail a student for not passing certain tests

### ISSUE THREAD

**Issue by 4onen** [adsnaider/StarGrade#1]
As the title says, it seems to me that some tests should be mandatory for receiving any score on the assignment, either because they should be necessary for the others to work or they are so elementary that no student working the assignment could fail to do so.

**Comment by adsnaider** [comment]
At the end of the day, the only thing Gradescope will accept is a score. What should the score be in this particular case? Zero? Will there be more that one of these mandatory tests? In that case what should the score be if some of the mandatory tests pass but not the other ones. Should the score be the same for someone that got 9/10 mandatory tests passing vs someone that got 1/10?

**Comment by 4onen** [comment]
You're right; this doesn't appear to be a common use case and likely stems from my inexperience in weighting assignments. Issue closed.
