### ISSUE TITLE
Large test suites may overload linux pipes and prevent test readout.

### ISSUE THREAD

**Issue by 4onen** [adsnaider/StarGrade#14]
https://github.com/adsnaider/StarGrade/blob/843e1bbf353c17a3f3defdb4644957aadbc697a8/stargrade/gradescope/gradescope_part_results.cc#L47

According to http://man7.org/linux/man-pages/man7/pipe.7.html we're limited to 16 pages (about 65k bytes) in a pipe, at which point further writes will block. Because the code here relies on the child process _completing fully_, this may enter a state where the test suite blocks on writing to the pipe and the parent process, blocked on waiting for the child, never completes.

Thought for future changes. I have not encountered this limit in practice yet.

**Comment by adsnaider** [comment]
This should get fixed with #15
