### ISSUE TITLE
Feature: Ability to have maximum suite score that is less than sum of maximum test scores

### ISSUE THREAD

**Issue by 4onen** [adsnaider/StarGrade#2]
As the title says, perhaps it's unreasonable for a student to get 80% if they fail some of the more heavily-weighted tests, simply because so many low-value tests exist. 

Example use case: I have a 10 point basic functionality test and some 40 points of individual corner-case tests. The student's code passes all corner cases but fails the primary functionality test. I'd like suite to have a max score of 25, such that this case would give them a 15/25 or below, but StarGrade's current implementation (insofar as I understand the configuration options) scores them at 40/50.

**Comment by adsnaider** [comment]
Hmm.. I'll have to think about this one. @4onen What is wrong with lowering the scores for the secondary tests?

**Comment by 4onen** [comment]
Evidently, nothing. Let's leave this out until we get a teacher request for it.
